<a href="https://colab.research.google.com/github/jeisettysaiteja/Machine-learning/blob/master/Bank_classification_using_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
data = pd.read_csv('Churn_Modelling.csv')
x = data.iloc[:, 3:-1]
y = data.iloc[:, -1]

In [ ]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x['Gender'] = le.fit_transform(data['Gender'])

In [ ]:
print(x)

      CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France       0  ...          1               1        101348.88
1             608     Spain       0  ...          0               1        112542.58
2             502    France       0  ...          1               0        113931.57
3             699    France       0  ...          0               0         93826.63
4             850     Spain       0  ...          1               1         79084.10
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France       1  ...          1               0         96270.64
9996          516    France       1  ...          1               1        101699.77
9997          709    France       0  ...          0               1         42085.58
9998          772   Germany       1  ...          1               0         92888.52
9999          792    France       0  ...          1              

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 1.0134888e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 1.1254258e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.1393157e+05]
 ...
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 4.2085580e+04]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 9.2888520e+04]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 3.8190780e+04]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [ ]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5396 - accuracy: 0.7319
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4528 - accuracy: 0.7980
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4389 - accuracy: 0.8001
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4323 - accuracy: 0.8015
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4288 - accuracy: 0.8025
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4258 - accuracy: 0.8039
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4236 - accuracy: 0.8050
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4206 - accuracy: 0.8050
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4181 - accuracy: 0.8062
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4157 - accura

In [ ]:
#Predicting the Test set results
y_pred = ann.predict(x_test)


In [ ]:
y_pred

array([[0.72759944],
       [0.1759646 ],
       [0.11582232],
       ...,
       [0.07110071],
       [0.28691065],
       [0.05639645]], dtype=float32)

In [ ]:
y_pred = y_pred > 0.5
y_pred

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
from sklearn.metrics import  confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1515   67]
 [ 207  211]]


0.863